### ISSUE TITLE
NERDTree defaults proposal

### ISSUE THREAD

**Issue by avesus** [nickserv/sane-defaults#5]
NERDTree has defaults not meeting expectations of those from Visual Studio world. Nothing works as expected. DIY product, as most of OSS.
Here’s my $500 spent .vimrc for NERDTree: https://gist.github.com/avesus/1954d9384d86cc1e39cb2b2eff7017b7

**Comment by nickserv** [comment]
Interesting config, thank you for the link. Since vim plugin management is kind of hairy, I would like to leave plugin configs like this outside of this project. However if you would like to make a version of it that doesn't depend on a bashrc I'd be happy to link to it here in case users are looking for related projects.
